# Generated by Django 5.2.5 on 2025-08-10 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.EmailField(default='user@example.com', max_length=254, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
